//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RabbitHouse.Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartElements
    {
        public int Id { get; set; }
        public int Count { get; set; }
        public System.DateTime RecordTime { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> ProductProperty_Id { get; set; }
        public System.Guid CartId { get; set; }
    
        public virtual ProductProperties ProductProperties { get; set; }
        public virtual Products Products { get; set; }
    }
}
