//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RabbitHouse.Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.CartElements = new HashSet<CartElements>();
            this.OrderDetails = new HashSet<OrderDetails>();
            this.ProductImages = new HashSet<ProductImages>();
            this.ProductProperties = new HashSet<ProductProperties>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> CurrentDiscount { get; set; }
        public Nullable<System.DateTime> DiscountStartTime { get; set; }
        public Nullable<System.DateTime> DiscountEndTime { get; set; }
        public System.DateTime PublishTime { get; set; }
        public bool IsSeasonalProduct { get; set; }
        public Nullable<System.DateTime> SaleStartTime { get; set; }
        public Nullable<System.DateTime> SaleEndTime { get; set; }
        public int CategoryId { get; set; }
        public string CoverImgUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartElements> CartElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ProductCategories ProductCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImages> ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductProperties> ProductProperties { get; set; }
    }
}
