// <auto-generated />
namespace RabbitHouse.Migrations.RabbitHouseDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSNToArticleDialog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSNToArticleDialog));
        
        string IMigrationMetadata.Id
        {
            get { return "201604250751176_AddSNToArticleDialog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
